version: '3.8'

services:
  # Model API service
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mlflow
    environment:
      - MODEL_PATH=models
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

  # MLflow tracking server
  mlflow:
    build: 
      context: .
      dockerfile: ./mlflow/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/tracking:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    command: mlflow server --host 0.0.0.0 --port 5000

  # Development environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    # This service is for development tasks (training, etc.)
    command: sleep infinity 