apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing-job
spec:
  template:
    spec:
      containers:
      - name: data-processor
        image: innovateanalytics/mlops-project:{{VERSION}}
        command: ["python", "-m", "src.data.process"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: models-volume
          mountPath: /models
        envFrom:
        - configMapRef:
            name: mlops-config
        - secretRef:
            name: mlops-secrets
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      restartPolicy: Never
  backoffLimit: 3 