apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-retraining
spec:
  schedule: "0 2 * * *"  # Run at 2 AM every day
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: model-trainer
            image: innovateanalytics/mlops-project:{{VERSION}}
            command: ["python", "-m", "src.models.train"]
            resources:
              requests:
                memory: "2Gi"
                cpu: "1000m"
              limits:
                memory: "4Gi"
                cpu: "2000m"
            volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: models-volume
              mountPath: /models
            envFrom:
            - configMapRef:
                name: mlops-config
            - secretRef:
                name: mlops-secrets
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pvc
          - name: models-volume
            persistentVolumeClaim:
              claimName: models-pvc
          restartPolicy: Never 