apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-project
  labels:
    app: mlops-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-project
  template:
    metadata:
      labels:
        app: mlops-project
    spec:
      containers:
      - name: mlops-project
        image: innovateanalytics/mlops-project:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
        envFrom:
        - configMapRef:
            name: mlops-config
        - secretRef:
            name: mlops-secrets
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MODEL_PATH
          value: "/app/models"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc 