apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: muhammadhaziq123/mlops-project:latest
        ports:
        - containerPort: 5000
        command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlruns
      volumes:
      - name: mlflow-data
        emptyDir: {} 