name: Continuous Integration

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, test, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint with flake8
        run: flake8 src tests
      - name: Check formatting with black
        run: black --check src tests
      - name: Sort imports with isort
        run: isort --check-only --profile black src tests
      - name: Type check with mypy
        run: mypy src

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests
        run: pytest tests --cov=src
      - name: Upload coverage report
        uses: codecov/codecov-action@v3 